version: '3.8'
services:
  mortgage-plan:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - "mysqlserver"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/mortgage-plan
    volumes:
      - ./:/app
    command: ./gradlew bootRun
    
  mysqlserver:
    image: mysql:8.0.23
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=mortgage-plan
      - MYSQL_PASSWORD=mortgage-plan
      - MYSQL_DATABASE=mortgage-plan
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: